---
title: "Simulation"
author: "Sean Anderson"
output: html_document
---

```{r}
library(sdmTMB)
library(ggplot2)
library(dplyr)
options(ggplot2.continuous.colour = "viridis")
```

```{r}
set.seed(42)
x <- runif(50, -1, 1)
y <- runif(50, -1, 1)
N <- length(x)
time_steps <- 5
X <- model.matrix(~ x1, data.frame(x1 = rnorm(N * time_steps)))
head(X)
loc <- data.frame(x = x, y = y)
plot(loc)
```

```{r}
mesh <- make_mesh(loc, xy_cols = c("x", "y"), cutoff = 0.1)
plot(mesh)
```

```{r}
s <- sdmTMB_sim(
  x = x, y = y, mesh = mesh, X = X,
  betas = c(0.5, 0.7), time_steps = time_steps, rho = 0.5,
  phi = 0.2, range = 0.8, sigma_O = 0, sigma_E = 0.3,
  seed = 123, family = poisson(link = "log")
)
head(s)
```

```{r}
ggplot(s, aes(x, y, colour = mu)) + geom_point() +
  scale_colour_continuous(trans = "log10")
```

```{r}
ggplot(s, aes(x, y, colour = as.numeric(observed))) + geom_point()
```

```{r}
mesh <- make_mesh(s, xy_cols = c("x", "y"), cutoff = 0.1)
m <- sdmTMB(
  data = s, formula = observed ~ x1,
  time = "time", spde = mesh,
  ar1_fields = TRUE, include_spatial = FALSE,
  family = poisson(link = "log")
)
tidy(m, conf.int = TRUE)
tidy(m, "ran_pars", conf.int = TRUE)
```

```{r}
p <- predict(m)
plot(s$mu, exp(p$est))
```

```{r}
m1 <- sdmTMB(
  data = s, formula = observed ~ 1,
  time = "time", spde = mesh,
  ar1_fields = TRUE, include_spatial = TRUE,
  family = poisson(link = "log")
)
AIC(m, m1)
```

# Cross validation

```{r}
spde <- make_mesh(pcod, c("X", "Y"), cutoff = 25)

# library(future) # for parallel processing
# plan(multisession) # for parallel processing
set.seed(2839)
m_cv <- sdmTMB_cv(
  density ~ 0 + depth_scaled + depth_scaled2,
  data = pcod, spde = spde, silent = FALSE,
  family = tweedie(link = "log"), k_folds = 3
)
m_cv$models[[1]]

head(m_cv$data)
m_cv$data$cv_fold[1:50]

cor(m_cv$data$density, m_cv$data$cv_predicted)
plot(m_cv$data$density, m_cv$data$cv_predicted)

m_cv$fold_loglik
m_cv$sum_loglik

set.seed(2839)
m_cv2 <- sdmTMB_cv(
  density ~ 0 + depth_scaled, 
  data = pcod, spde = spde, silent = FALSE,
  family = tweedie(link = "log"), k_folds = 3
)
m_cv$sum_loglik
m_cv2$sum_loglik

AIC(m_cv$models[[1]], m_cv2$models[[1]])
AIC(m_cv$models[[2]], m_cv2$models[[2]])
```

